apiVersion: v1
kind: ReplicationController
metadata:
  name: my-nginx-replication-controller
  labels: 
    type: learn-po
spec:
  template:
    metadata:
      name: rc-nginx-po
      labels:
        type: learn-po
        font: arial 
    spec:
      containers:
        - image: nginx
          name: nginx-rc-container
  replicas: 2
  selector:
      type: learn-po
      font: arial 


