apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-nginx-replica-set
  labels:
    type: learn-po
spec:
  template:
    metadata:
      name: rc-nginx-po
      labels:
        type: learn-po
        font: arial 
    spec:
      containers:
        - image: nginx
          name: nginx-rs-container
  replicas: 2
  selector:
    matchLabels:
      type: learn-po        

